[alt]
url = "http://ftp.altlinux.org/pub/distributions/ALTLinux/images/Sisyphus/cloud/{{arch}}/alt-sisyphus-cloud-{{arch}}.qcow2"
description = "ALT Linux Sisyphus"
change = ["update-all", "delete"]

[alt-p11]
url = "http://ftp.altlinux.org/pub/distributions/ALTLinux/images/p11/cloud/{{arch}}/alt-p11-cloud-{{arch}}.qcow2"
description = "ALT Linux p11"
change = ["update-all", "delete"]

[alt-p10]
url = "http://ftp.altlinux.org/pub/distributions/ALTLinux/images/p10/cloud/{{arch}}/alt-p10-cloud-{{arch}}.qcow2"
description = "ALT Linux p10"
change = ["update-all", "delete"]

[alt-p9]
url = "http://ftp.altlinux.org/pub/distributions/ALTLinux/images/p9/cloud/{{arch}}/alt-p9-cloud-{{arch}}.qcow2"
description = "ALT Linux p9"
change = ["update-all", "delete"]

[alt-sisyphus]
url = "http://ftp.altlinux.org/pub/distributions/ALTLinux/images/Sisyphus/cloud/{{arch}}/alt-sisyphus-cloud-{{arch}}.qcow2"
description = "ALT Linux Sisyphus"
change = ["update-all", "delete"]

[alt-gui]
url = "http://ftp.altlinux.org/pub/distributions/ALTLinux/images/p10/cloud/{{arch}}/alt-p10-workstation-cloud-{{arch}}.qcow2"
description = "ALT Linux p10 gui"
properties = ["gui"]
change = ["update-all", "delete"]

[arch]
description = "Archlinux"
url = ""
get-url-prog = "vml-get-arch"
change = ["update-all", "delete"]

[ubuntu]
url = "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-{{arch}}.img"
description = "latest Ubuntu release (24.04)"
change = ["update-all", "delete"]

[ubuntu.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[ubuntu-lts]
url = "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-{{arch}}.img"
description = "latest LTS Ubuntu release (24.04)"
change = ["update-all", "delete"]

[ubuntu-lts.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[ubuntu-oracular]
url = "https://cloud-images.ubuntu.com/oracular/current/oracular-server-cloudimg-{{arch}}.img"
description = "Ubuntu 24.10 Oracular Oriole Daily Build"
change = ["update-all", "delete"]

[ubuntu-oracular.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[ubuntu-noble]
url = "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-{{arch}}.img"
description = "Ubuntu 24.04 Noble Numbat"
change = ["update-all", "delete"]

[ubuntu-noble.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[ubuntu-jammy]
url = "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-{{arch}}.img"
description = "Ubuntu 22.04 Jammy Jellyfish"
change = ["update-all", "delete"]

[ubuntu-jammy.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[ubuntu-focal]
url = "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-{{arch}}.img"
description = "Ubuntu 20.04 Focal Fossa"
change = ["update-all", "delete"]

[ubuntu-focal.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[ubuntu-bionic]
url = "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-{{arch}}.img"
description = "Ubuntu 18.04 Bionic Beaver"
change = ["update-all", "delete"]

[ubuntu-bionic.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[debian]
url = "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-{{arch}}.qcow2"
description = "Debian stable"
change = ["update-all", "delete"]

[debian.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[debian-13]
url = "https://cloud.debian.org/images/cloud/trixie/daily/latest/debian-13-genericcloud-{{arch}}-daily.qcow2"
description = "Debian trixie (testing)"
change = ["update-all", "delete"]

[debian-13.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[debian-12]
url = "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-{{arch}}.qcow2"
description = "Debian bookworm (stable)"
change = ["update-all", "delete"]

[debian-12.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[debian-11]
url = "https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-{{arch}}.qcow2"
description = "Debian bullseye (oldstable)"
change = ["update-all", "delete"]

[debian-11.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[debian-10]
url = "https://cloud.debian.org/images/cloud/buster/latest/debian-10-genericcloud-{{arch}}.qcow2"
description = "Debian buster (oldoldstable)"
change = ["update-all", "delete"]

[debian-10.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[debian-9]
url = "https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-{{arch}}.qcow2"
description = "Debian stretch (oldoldoldstable)"
change = ["update-all", "delete"]

[debian-9.arch-mapping]
x86_64 = "amd64"
aarch64 = "arm64"

[alma]
url = "https://repo.almalinux.org/almalinux/9/cloud/{{arch}}/images/AlmaLinux-9-GenericCloud-latest.{{arch}}.qcow2"
description = "AlmaLinux latest (9)"
change = ["update-all", "delete"]

[alma-9]
url = "https://repo.almalinux.org/almalinux/9/cloud/{{arch}}/images/AlmaLinux-9-GenericCloud-latest.{{arch}}.qcow2"
description = "AlmaLinux"
change = ["update-all", "delete"]

[alma-8]
url = "https://repo.almalinux.org/almalinux/8/cloud/{{arch}}/images/AlmaLinux-8-GenericCloud-latest.{{arch}}.qcow2"
description = "AlmaLinux 8"
change = ["update-all", "delete"]

[rocky]
url = "https://dl.rockylinux.org/pub/rocky/9/images/{{arch}}/Rocky-9-GenericCloud.latest.{{arch}}.qcow2"
description = "Rocky Linux latest (9)"
change = ["update-all", "delete"]

[rocky-9]
url = "https://dl.rockylinux.org/pub/rocky/9/images/{{arch}}/Rocky-9-GenericCloud.latest.{{arch}}.qcow2"
description = "Rocky Linux 9"
change = ["update-all", "delete"]

[rocky-8]
url = "https://dl.rockylinux.org/pub/rocky/8/images/{{arch}}/Rocky-8-GenericCloud.latest.{{arch}}.qcow2"
description = "Rocky Linux 8"
change = ["update-all", "delete"]

[centos]
url = ""
get-url-prog = "vml-get-centos"
description = "CentOS latest stream (9)"
change = ["update-all", "delete"]

[centos-stream]
url = ""
get-url-prog = "vml-get-centos"
description = "CentOS latest stream (9)"
change = ["update-all", "delete"]

[centos-9-stream]
url = ""
get-url-prog = "vml-get-centos"
description = "CentOS 9-stream"
change = ["update-all", "delete"]

[centos-8-stream]
url = ""
get-url-prog = "vml-get-centos"
description = "CentOS 8-stream"
change = ["update-all", "delete"]

[centos-8]
url = ""
get-url-prog = "vml-get-centos"
description = "CentOS 8"
change = ["update-all", "delete"]

[centos-7]
url = "https://cloud.centos.org/centos/7/images/CentOS-7-{{arch}}-GenericCloud.qcow2"
description = "CentOS 7"
change = ["update-all", "delete"]

[fedora]
url = "https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/{{arch}}/images/Fedora-Cloud-Base-Generic.{{arch}}-40-1.14.qcow2"
description = "latest Fedora release (40)"
change = ["update-all", "delete"]

[fedora-rawhide]
url = ""
get-url-prog = "vml-get-fedora-rawhide"
description = "Fedora Rawhide"
change = ["update-all", "delete"]

[fedora-40]
url = "https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/{{arch}}/images/Fedora-Cloud-Base-Generic.{{arch}}-40-1.14.qcow2"
description = "Fedora 40"
change = ["update-all", "delete"]

[fedora-39]
url = "https://download.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/{{arch}}/images/Fedora-Cloud-Base-39-1.5.{{arch}}.qcow2"
description = "Fedora 39"
change = ["update-all", "delete"]

[fedora-38]
url = "https://download.fedoraproject.org/pub/fedora/linux/releases/38/Cloud/{{arch}}/images/Fedora-Cloud-Base-38-1.6.{{arch}}.qcow2"
description = "Fedora 38"
change = ["update-all", "delete"]

[fedora-37]
url = "https://download.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/{{arch}}/images/Fedora-Cloud-Base-37-1.7.{{arch}}.qcow2"
description = "Fedora 37"
change = ["update-all", "delete"]

[opensuse]
url = "https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/openSUSE-Tumbleweed/openSUSE_Tumbleweed{% if arch == 'aarch64' %}_ARM{% endif %}/openSUSE-Tumbleweed-Minimal-VM.{{arch}}-Cloud.qcow2"
description = "openSUSE Tumbleweed"
change = ["update-all", "delete"]

[opensuse-leap]
url = "https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/openSUSE-Leap-15.6/images/openSUSE-Leap-15.6-Minimal-VM.{{arch}}-Cloud.qcow2"
description = "openSUSE Leap 15.6"
change = ["update-all", "delete"]

[opensuse-tumbleweed]
url = "https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/openSUSE-Tumbleweed/openSUSE_Tumbleweed{% if arch == 'aarch64' %}_ARM{% endif %}/openSUSE-Tumbleweed-Minimal-VM.{{arch}}-Cloud.qcow2"
description = "openSUSE Tumbleweed"
change = ["update-all", "delete"]
